Brenno
Univesp-PIs/DRP04-PJI240-BACK pull request #13
Opened 2024-10-07 03:34 UTC by brenno-workflow

2024-10-09 01:51 UTC, vitor-rc1 requested changes

2024-10-09 01:51 UTC, vitor-rc1 commented on docs/mocks/.old/curriculum/DELETAR-curriculum-payload.json
> +{
Esses arquivos do curriculum deveriam estar aqui mesmo?

2024-10-09 01:51 UTC, vitor-rc1 commented on .env
> +SECRET_KEY="django-insecure-qbj*e#r+2=dbq78h=e_bte-(h%5blc6_t2(+9zj+a!7ry4jv(s"
Esse tipo de informação jamais deve ser comitada.
Nestes casos o ideal é usar as [secrets](https://github.com/Univesp-PIs/DRP04-PJI240-BACK/settings/secrets/actions) do repositorio

2024-10-11 17:29 UTC, brenno-workflow commented on docs/mocks/.old/curriculum/DELETAR-curriculum-payload.json
> +{
Eu estou usando apenas como base para lembrar dos caminhos anteriores.
No ultimo commit, eu vou apagar essas pastas .old

2024-10-12 19:07 UTC, brenno-workflow reviewed
Ok

2024-10-20 13:28 UTC, VitorScolari approved these changes

2024-10-20 13:58 UTC, vitor-rc1 approved these changes

2024-10-20 14:42 UTC, merged